// for auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// for promotions failed
export const PROMOS_FAILED = 'PROMOS_FAILED';

// for host promotions
export const DELETE_HOST_PROMO = 'DELETE_HOST_PROMO';
export const UPDATE_HOST_PROMO = 'UPDATE_HOST_PROMO';
export const HOST_PROMOS_LOADING = 'HOST_PROMOS_LOADING';
export const ADD_HOST_PROMOS = 'ADD_HOST_PROMOS';
export const ADD_HOST_PROMO = 'ADD_HOST_PROMO';

// for system promotions
export const DELETE_SYSTEM_PROMO = 'DELETE_SYSTEM_PROMO';
export const UPDATE_SYSTEM_PROMO = 'UPDATE_SYSTEM_PROMO';
export const SYSTEM_PROMOS_LOADING = 'SYSTEM_PROMOS_LOADING';
export const ADD_SYSTEM_PROMOS = 'ADD_SYSTEM_PROMOS';
export const ADD_SYSTEM_PROMO = 'ADD_SYSTEM_PROMO';

// for homeposts
export const HOMEPOSTS_LOADING = 'HOMEPOSTS_LOADING';
export const ADD_HOMEPOSTS = 'ADD_HOMEPOSTS';
export const ADD_HOMEPOST = 'ADD_HOMEPOST';
export const UPDATE_HOMEPOST = 'UPDATE_HOMEPOST';
export const HOMEPOSTS_FAILED = 'HOMEPOSTS_FAILED';
export const UPDATE_CURRENT_HOMEPOST = 'UPDATE_CURRENT_HOMEPOST';

// for ratings 
export const ADD_RATING = 'ADD_RATING';
export const ADD_RATINGS = 'ADD_RATINGS';
export const RATINGS_FAILED = 'RATINGS_FAILED';
 

// for favorites
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

// for search
export const UPDATE_RESULT_HOMES_QUERY = 'UPDATE_RESULT_HOMES_QUERY'
