const HOMEPOSTS = [
    {
        owner: 'host',
        weekdayPrice: 100000,
        weekendPrice: 500000,
        minimumNights: 1,
        name: 'Double bed - Garden view - Hồng trứng',
        description: 'Cho những trải nghiệm bình yên và dung dị, nơi đây dành cho những ai thích một Đà Lạt “khác”. Một Đà Lạt không phố phường, xe cộ khói bụi qua lại. Bởi nơi đây nằm ngay lưng đồi, lọt thỏm giữa thung lũng đèn vàng, đồi thông và vườn dâu xanh ngát.',
        image: [],
        typeHome: 'Chung cư',
        typeRoom: 'Phòng riêng',
        acreage: 100,
        maxPeoples: 5,
        numBed: 3,
        numBedroom: 3,
        numBathroom: 1,
        location: '',
        state: 'waiting',
        confirmedBy: '',
        rating: [],
    },
    {
        owner: 'host',
        weekdayPrice: 200000,
        weekendPrice: 800000,
        minimumNights: 2,
        name: 'THE HOBBIT BUNGALOW - STANDARD',
        description: '',
        image: [],
        typeHome: 'Khác',
        typeRoom: 'Nguyên căn',
        acreage: 367,
        maxPeoples: 10,
        numBed: 6,
        numBedroom: 4,
        numBathroom: 2,
        location: '',
        state: 'waiting',
        confirmedBy: '',
        rating: [],
    }
]